# Generated by Django 4.2.20 on 2025-07-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproject',
            name='footer_text_content',
            field=models.TextField(blank=True, verbose_name='頁尾文字內容'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='test_project_logos/', verbose_name='頁首Logo'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='header_text_content',
            field=models.TextField(blank=True, verbose_name='頁首文字內容'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='personal_share_footer_content',
            field=models.TextField(blank=True, verbose_name='個人分享頁尾內容'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='personal_share_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='個人分享標題名稱'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='advantage_suggestions',
            field=models.TextField(blank=True, verbose_name='優勢建議'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='content',
            field=models.TextField(blank=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='development_direction',
            field=models.TextField(blank=True, verbose_name='發展方向'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='role_image',
            field=models.ImageField(blank=True, null=True, upload_to='role_images/', verbose_name='角色圖'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='role_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='角色名稱'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='score_type_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='分數類型名稱'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='tag_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tag文字'),
        ),
    ]
