# Generated by Django 4.2.20 on 2025-07-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testproject_footer_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprojectcategory',
            name='english_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='英文名稱'),
        ),
    ]
