# Generated by Django 4.2.20 on 2025-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testprojectcategory_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinvitee',
            name='status',
            field=models.CharField(choices=[('employed', '在職'), ('job_seeker', '求職者')], default='employed', max_length=20, verbose_name='狀態'),
        ),
    ]
