# Generated by Django 4.2.20 on 2025-07-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testinvitee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testproject',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='簡介'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='precautions',
            field=models.TextField(blank=True, verbose_name='注意事項'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='title_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='標題名稱'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='title_name_english',
            field=models.CharField(blank=True, max_length=200, verbose_name='標題名稱英文'),
        ),
        migrations.AddField(
            model_name='testproject',
            name='usage_guide',
            field=models.TextField(blank=True, verbose_name='使用方式'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='development_parameter_content',
            field=models.TextField(blank=True, verbose_name='發展建議參數內容'),
        ),
        migrations.AddField(
            model_name='testprojectcategory',
            name='development_parameter_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='發展建議參數名稱'),
        ),
    ]
