# Generated by Django 4.2.20 on 2025-07-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testproject_introduction_testproject_precautions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprojectcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='說明'),
        ),
    ]
