# Generated by Django 4.2.20 on 2025-07-16 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testprojectcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='購買時間')),
                ('first_access_date', models.DateTimeField(blank=True, null=True, verbose_name='首次進入時間')),
                ('last_access_date', models.DateTimeField(blank=True, null=True, verbose_name='最後進入時間')),
                ('access_count', models.IntegerField(default=0, verbose_name='進入次數')),
                ('status', models.CharField(choices=[('purchased', '已購買'), ('in_progress', '進行中'), ('completed', '已完成'), ('expired', '已過期')], default='purchased', max_length=20, verbose_name='狀態')),
                ('points_consumed', models.IntegerField(default=1, verbose_name='消費點數')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('point_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pointtransaction', verbose_name='點數交易記錄')),
                ('test_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_records', to='core.testproject', verbose_name='測驗項目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_test_records', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '個人測驗記錄',
                'verbose_name_plural': '個人測驗記錄',
                'db_table': 'individual_test_record',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'test_project')},
            },
        ),
    ]
