# Generated by Django 4.2.20 on 2025-07-16 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_individualtestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始測驗數據')),
                ('processed_data', models.JSONField(default=dict, verbose_name='處理後數據')),
                ('score_value', models.FloatField(blank=True, null=True, verbose_name='評分值')),
                ('prediction_value', models.TextField(blank=True, verbose_name='預測值')),
                ('category_results', models.JSONField(default=dict, verbose_name='分類結果')),
                ('trait_results', models.JSONField(default=dict, verbose_name='特質結果')),
                ('test_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='測驗完成時間')),
                ('external_test_id', models.CharField(blank=True, max_length=100, verbose_name='外部測驗ID')),
                ('test_url', models.URLField(blank=True, verbose_name='測驗結果原始連結')),
                ('result_status', models.CharField(choices=[('pending', '等待結果'), ('manual_input', '手動輸入'), ('auto_crawled', '自動爬取'), ('completed', '結果完整'), ('failed', '獲取失敗')], default='pending', max_length=20, verbose_name='結果狀態')),
                ('crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='結果爬取時間')),
                ('crawl_attempts', models.IntegerField(default=0, verbose_name='爬取嘗試次數')),
                ('crawl_error_message', models.TextField(blank=True, verbose_name='爬取錯誤訊息')),
                ('report_generated', models.BooleanField(default=False, verbose_name='報告已生成')),
                ('report_path', models.CharField(blank=True, max_length=500, verbose_name='報告路徑')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='報告生成時間')),
                ('allow_sharing', models.BooleanField(default=False, verbose_name='允許分享結果')),
                ('notes', models.TextField(blank=True, verbose_name='個人備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('individual_test_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='core.individualtestrecord', verbose_name='個人測驗記錄')),
                ('test_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.testproject', verbose_name='測驗項目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_test_results', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '個人測驗結果',
                'verbose_name_plural': '個人測驗結果',
                'db_table': 'individual_test_result',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'test_project'], name='individual__user_id_ecb56b_idx'), models.Index(fields=['result_status'], name='individual__result__ed9d1f_idx'), models.Index(fields=['-created_at'], name='individual__created_ed1a73_idx')],
            },
        ),
    ]
