# Generated by Django 4.2.20 on 2025-07-18 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_individualtestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('crawl_all_pending_results', '批量爬取測驗結果'), ('cleanup_old_crawl_logs', '清理舊日誌'), ('manual_crawl', '手動爬取')], max_length=100, verbose_name='任務名稱')),
                ('status', models.CharField(choices=[('pending', '待執行'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗')], default='completed', max_length=20, verbose_name='執行狀態')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功數量')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失敗數量')),
                ('total_count', models.IntegerField(default=0, verbose_name='總數量')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='執行時間')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='執行時長')),
                ('message', models.TextField(blank=True, verbose_name='執行訊息')),
                ('error_details', models.TextField(blank=True, verbose_name='錯誤詳情')),
            ],
            options={
                'verbose_name': '爬蟲執行日誌',
                'verbose_name_plural': '爬蟲執行日誌',
                'db_table': 'crawler_logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
