# Generated by Django 4.2.20 on 2025-07-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_crawlerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='test_platform_password',
            field=models.CharField(blank=True, help_text='用於自動登入測驗平台的密碼', max_length=255, null=True, verbose_name='測驗平台密碼'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='test_platform_username',
            field=models.CharField(blank=True, help_text='用於自動登入測驗平台的帳號', max_length=100, null=True, verbose_name='測驗平台帳號'),
        ),
    ]
