# Generated by Django 4.2.20 on 2025-07-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_test_platform_login_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprojectassignment',
            name='test_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_assignments', to='core.testproject', verbose_name='測驗項目'),
        ),
    ]
