# Generated by Django 4.2.20 on 2025-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_crawlerdetaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='tax_id',
            field=models.CharField(db_index=True, max_length=8, verbose_name='統一編號'),
        ),
        migrations.AddConstraint(
            model_name='enterpriseprofile',
            constraint=models.UniqueConstraint(fields=('user', 'tax_id'), name='unique_enterprise_user_tax_id'),
        ),
    ]
